[package]
name = "aoc"
version = "0.1.0"
edition = "2021"
description = "Ergonomic advent of code solutions in Rust"

[dependencies]
aoc-client = "0.2.0"
clap = { version = "4", features = ["cargo", "color", "derive"]}
exit-code = "1.0"
